[package]
name = "tree-clone-rs"
version = "0.1.0"
authors = ["Arnav Borborah <arnavborborah11@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.clap]
version = "2.32.0"
default-features = false
features = ["suggestions"]
